### ISSUE TITLE
component InputNumber's content does not display center，cause by the 【-webkit-inner-spin-button】

### ISSUE THREAD

**Issue by ivyhaswell** [eleme/element-angular#309]
Issue Type:
- [* ] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  

Description:

![image](https://user-images.githubusercontent.com/13186709/33866603-9c0bbd90-df32-11e7-940a-802add2c40fb.png)

**Comment by WittBulter** [comment]
thanks.

fixed, #311 . a repair version will be released in today.

**Comment by ivyhaswell** [comment]
still not display central,  `visibility: hidden` does not work, the spin's hidden, but still occupied the space.

**Comment by WittBulter** [comment]
i will follow up

**Comment by WittBulter** [comment]
thanks so much, join the code review (#315) plz. 🙂
